version: 2

project_name: machinist

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - main: ./cmd/machinist
    binary: machinist
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{.Version}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: moinsen-dev
    name: machinist
  draft: false
  prerelease: auto
